on: [push]

jobs:
  pull:
    runs-on: ubuntu-latest
    name: pull test
    steps:
      - uses: actions/checkout@v3
      - uses: Warashi/actions-cache-docker-pull@main
      - run: systemctl show docker
      - run: systemctl status docker
      - run: docker info
      - run: docker compose -f .github/docker-compose-for-test.yml pull
      - run: sudo journalctl -u docker
      - name: Dump docker logs
        uses: jwalton/gh-docker-logs@v2
