on: [push]

jobs:
  pull:
    runs-on: ubuntu-latest
    name: pull test
    steps:
      - uses: Warashi/actions-cache-docker-pull@main
      - run: |
          cat /etc/systemd/system/docker.service
      - run: docker pull nginx
