on: [push]

jobs:
  pull:
    runs-on: ubuntu-latest
    name: pull test
    steps:
      - uses: Warashi/actions-cache-docker-pull@main
      - run: systemctl show docker
      - run: systemctl status docker
      - run: docker info
      - run: docker pull nginx
      - name: Dump docker logs
        uses: jwalton/gh-docker-logs@v2
